services:

  rating-service:
    container_name: rating-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - coursehub-net

  rating_service_postgres:
    container_name: rating_service_postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "${RATING_DB}"
      POSTGRES_USER: "${RATING_USER}"
      POSTGRES_PASSWORD: "${RATING_PASS}"
    ports:
      - "5435:5432"
    volumes:
      - rating_postgres_data:/var/lib/postgresql/data
    networks:
      - coursehub-net

networks:
  coursehub-net:
    driver: bridge

volumes:
  rating_postgres_data:
