spring:
  application:
    name: rating-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5435/ch_rts_db
    username: ch_rts_user
    password: dbhunter
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: coursehub_rabbit_mq
    password: 5yZ<ox6qscG0


server:
  port: 8084


services:
  identity:
    secret-key: Z+2hXkMTIW+S3IlblVk48SRQgy31QhFu25BP84SNlSU=

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true